# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08PB.proto\x12\x02\x41\x33\"[\n\x04\x42ook\x12\x0c\n\x04isbn\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x0c\n\x04year\x18\x04 \x01(\x05\x12\x18\n\x05genre\x18\x05 \x01(\x0e\x32\t.A3.Genre\"f\n\rInventoryItem\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x18\n\x04\x62ook\x18\x02 \x01(\x0b\x32\x08.A3.BookH\x00\"\"\n\x06Status\x12\r\n\tAVAILABLE\x10\x00\x12\t\n\x05TAKEN\x10\x01\x42\x07\n\x05Media*,\n\x05Genre\x12\n\n\x06HORROR\x10\x00\x12\n\n\x06\x43OMEDY\x10\x01\x12\x0b\n\x07ROMANCE\x10\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PB_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENRE._serialized_start=213
  _GENRE._serialized_end=257
  _BOOK._serialized_start=16
  _BOOK._serialized_end=107
  _INVENTORYITEM._serialized_start=109
  _INVENTORYITEM._serialized_end=211
  _INVENTORYITEM_STATUS._serialized_start=168
  _INVENTORYITEM_STATUS._serialized_end=202
# @@protoc_insertion_point(module_scope)
